apiVersion: apps/v1 
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web 
    spec:
      containers:
      - name: node-app 
        image: muralisocial123/node-app-example:latest
        ports:
        - containerPort: 3000
