apiVersion: v1 
kind: Pod 
metadata:
  name: node-app 
spec: 
  containers:
    - name: node-web 
      image: muralisocial123/node-app-example:latest
      ports: 
        - containerPort: 3000
    - name: web-app 
      image: muralisocial123/web-app-test:latest
      ports:
        - containerPort: 80